### ISSUE TITLE
M1 : Building tools

### ISSUE THREAD

**Issue by malov** [matruss/anvil#2]
We all know Gradle, and it's one of the options, but I'm learning towards trying SBT again - it became kind of a standard in Scala/Open-source world.

**Comment by malov** [comment]
Ok, I have a spare time now, and I'd itching to start and I'm going to use SBT. Unless someone who potentially be writing code here (I'd assume @btrofimov or @nshmatko - right ?) have something to say, I'm sticking to it.

**Comment by btrofimov** [comment]
SBT +1

**Comment by malov** [comment]
I'm sure @nshmatko would like this idea too :)

**Comment by nshmatko** [comment]
Sure, let's use SBT

**Comment by malov** [comment]
Settled then !
